puzzles/urls.py
from django.urls import path

from . import views

app_name = "puzzles"
urlpatterns = [
    path("", views.landing, name="landing"),
    path("hunt/<int:hunt_id>/", views.bigboard, name="bigboard"),
    path("puzzle/<int:puzzle_id>/", views.puzzlepage, name="puzzlepage"),
    path("puzzle/<int:puzzle_id>/update", views.update, name="update"),
    path("hunt/<int:hunt_id>/new_round", views.new_round, name="new_round"),
    path("hunt/<int:hunt_id>/new_puzzle", views.new_puzzle, name="new_puzzle"),

    
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("auth/", views.auth, name="auth"),
    path("userpage/", views.user_page, name="userpage"),
    path("userpage/update", views.update_discord_user, name="update_discord_user")
]

web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("puzzles.urls"))
]

puzzles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from . import google

class Theme(models.TextChoices):
    LATTE = "latte", "Latte"
    FRAPPE = "frappe", "Frappé"
    MACCHIATO = "macchiato", "Macchiato"
    MOCHA = "mocha", "Mocha"

class Color(models.TextChoices):
    ROSEWATER = "rosewater", "Rosewater"
    FLAMINGO = "flamingo", "Flamingo"
    PINK = "pink", "Pink"
    MAUVE = "mauve", "Mauve"
    RED = "red", "Red"
    MAROON = "maroon", "Maroon"
    PEACH = "peach", "Peach"
    YELLOW = "yellow", "Yellow"
    GREEN = "green", "Green"
    TEAL = "teal", "Teal"
    SKY = "sky", "Sky"
    SAPPHIRE = "sapphire", "Sapphire"
    BLUE = "blue", "Blue"
    LAVENDER = "lavender", "Lavender"

class DiscordUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cached_username = models.CharField(max_length=64)

    linked_gmail = models.EmailField(blank=True, max_length=255)
    chosen_theme = models.CharField(max_length=9, choices=Theme.choices, default=Theme.MOCHA)
    chat_color = models.CharField(max_length=9, choices=Color.choices, default=Color.BLUE)

    def __str__(self):
        return f"{self.cached_username}"

class PuzzleStatus(models.TextChoices):
    LOCKED = 'LO', "Locked"
    NOT_STARTED = 'NS', "Not Started"
    IN_PROGRESS = 'IP', "In Progress"
    STUCK = 'ST', "Stuck"
    NES = 'EX', "Now Extract Somehow" 
    SOLVED = 'SL', "Solved"

    # Return the starting priority value of a puzzle type
    @staticmethod
    def default_priority(status):
        if status == PuzzleStatus.LOCKED:
            return 0.2 # This is nonzero to account for locked metas
        elif status == PuzzleStatus.NOT_STARTED:
            return 1.3
        elif status == PuzzleStatus.IN_PROGRESS:
            return 1
        elif status == PuzzleStatus.STUCK:
            return 1.75
        elif status == PuzzleStatus.NES:
            return 2
        elif status == PuzzleStatus.SOLVED:
            return 0

class Hunt(models.Model):
    name = models.CharField(max_length=255)

    team_user = models.CharField(max_length=64)
    team_pw = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"
    
    def count_puzzles_of_status(self, status: PuzzleStatus):
        return self.puzzle_set.filter(status__exact=status).count()
    
    def total_puzzles(self):
        return self.puzzle_set.count()
    
    def num_locked(self):
        return self.count_puzzles_of_status(PuzzleStatus.LOCKED)

    def num_solved(self):
        return self.count_puzzles_of_status(PuzzleStatus.SOLVED)
    
    def num_available(self):
        return self.total_puzzles() - self.num_solved() - self.num_locked()
    
    def meta_solves(self):
        return self.puzzle_set.filter(status__exact=PuzzleStatus.SOLVED, is_meta__exact=True).count()

    def roundless_puzzles(self):
        return self.puzzle_set.filter(rounds=None).all()
    
    def top_prio_puzzles(self):
        puzzle_max = 10
        puzzles = self.puzzle_set.filter(~models.Q(status__exact=PuzzleStatus.SOLVED)).all()[:puzzle_max]
        return sorted(puzzles, key=(lambda p: (-p.priority(), p.name)))
        

class Round(models.Model):
    name = models.CharField(max_length=255)
    hunt = models.ForeignKey(Hunt, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    def puzzles_ordered(self):
        # TODO: human sort the name? We might have something weird like shell game with numbered puzzles that goes over 10?
        return self.puzzle_set.order_by("-is_meta", "name").all()
    
    # An extra multiplier on the puzzles of this round based on its meta structure
    def priority_multiplier(self):
        num_metas = self.puzzle_set.filter(is_meta=True).count()

        # This round has no metas, no adjustment
        if num_metas == 0:
            return 1
        
        solved_metas = self.puzzle_set.filter(models.Q(is_meta=True) and ~models.Q(status=PuzzleStatus.SOLVED)).count()
        unsolved_metas = num_metas - solved_metas

        # This round has metas, but all of them are solved, so we lower the round's priority
        if unsolved_metas == 0:
            return 0.25 # Nonzero in case a feeder used elsewhere is prioritized
        
        # This round has exactly one unsolved meta and no other metas. Give it massive priority. 
        if num_metas == unsolved_metas and num_metas == 1:
            return 10
        
        # TODO: if we ever explicitly enable setting puzzles as feeders to metas, account for that
        num_feeders = self.puzzle_set.filter(is_meta=False).count()

        # This round has only metas. It's probably *extremely* important. Give it brobdingnagian priority.
        if num_feeders == 0:
            return 50

        # This round has multiple metas and some non-meta feeders and thus something weird is going on. 
        # It is not quite as important as a feederless round, but still more important than a 1 meta round
        # so we give it a merely falstaffian priority 
        return 25


class Puzzle(models.Model):
    name = models.CharField(max_length=255)
    hunt = models.ForeignKey(Hunt, on_delete=models.CASCADE)
    rounds = models.ManyToManyField(Round, through="PuzzleRoundField")
    url = models.URLField()
    is_meta = models.BooleanField(default=False)
    sheet_id = models.CharField(max_length=255, default="")
    description = models.CharField(max_length=1000, default="")

    status = models.CharField(max_length=2, choices=PuzzleStatus.choices, default=PuzzleStatus.LOCKED)

    def __str__(self):
        return f"{self.name}"
    
    def regenerate_puzzle_sheet(self):
        # This won't delete the old sheet, but it will make the site show you the new one.
        self.sheet_id = google.make_puzzle_sheet(f"{self.name}")
        self.save()

    def rename_puzzle_sheet(self):
        google.rename_sheet(self.sheet_id, self.name)

    def sheet_url(self):
        # Make a sheet if one does not exist
        if self.sheet_id == "":
            self.regenerate_puzzle_sheet()
        
        return f"https://docs.google.com/spreadsheets/d/{self.sheet_id}/edit"
    
    def priority(self):
        # Solved puzzles have 0 priority, no need to do any further math
        if self.status == PuzzleStatus.SOLVED:
            return 0
        
        priority = PuzzleStatus.default_priority(self.status)

        for hunt_round in self.rounds.all():
            priority *= hunt_round.priority_multiplier()

        # Metas are highly prioritized above and beyond their round multipliers
        if self.is_meta:
            priority *= 10

        # An unsolved puzzle with answers??? How strange. Give it a priority boost.
        if self.answer_set.count() > 0:
            priority *= 1.5

        return priority


class PuzzleRoundField(models.Model):
    puzzle = models.ForeignKey(Puzzle, on_delete=models.CASCADE)
    hunt_round  = models.ForeignKey(Round, on_delete=models.CASCADE)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["puzzle", "hunt_round"], name="no_duplicate_links"),
        ]

    def clean(self):
        if self.puzzle.hunt.id != self.hunt_round.hunt.id:
                raise ValidationError(f"Round {self.hunt_round.name} is not in hunt {self.puzzle.hunt.name}")

class Answer(models.Model):
    answer_text = models.CharField(max_length=255)
    puzzle = models.ForeignKey(Puzzle, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.answer_text}"


class ChatMessage(models.Model):
    puzzle = models.ForeignKey(Puzzle, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sent_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    is_system = models.BooleanField(default=False)

    class Meta:
        constraints = [
            # is_system true => user null
            models.CheckConstraint(
                condition = models.Q(is_system=False) | models.Q(user__isnull=True),
                name = "system_messages_have_null_user"),
        ]


    def __str__(self):
        return self.content

puzzles/forms.py
from django import forms
from .models import PuzzleStatus, Puzzle, Answer, DiscordUser, Theme, Color


class NewPuzzleForm(forms.Form):
    name = forms.CharField(label="Puzzle Name", max_length=255)
    description = forms.CharField(label="Description", max_length=1000, required=False)
    status = forms.ChoiceField(choices=PuzzleStatus.choices)
    rounds = forms.MultipleChoiceField(choices=[])
    url = forms.URLField(label="Puzzle URL", required=False)
    is_meta = forms.BooleanField(label="Meta?", required=False)

    def __init__(self, hunt, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.hunt = hunt
        
        self.fields["rounds"] = forms.MultipleChoiceField(choices=[
            (r.id, r.name) for r in hunt.round_set.all()
        ])

    # TODO: this sucks
    def make_puzzle(self):
        puzzle = Puzzle()
        puzzle.name = self.cleaned_data["name"]
        puzzle.hunt = self.hunt
        puzzle.status = self.cleaned_data["status"]
        puzzle.url = self.cleaned_data["url"]
        puzzle.is_meta = self.cleaned_data["is_meta"]
        puzzle.description = self.cleaned_data["description"]
        puzzle.regenerate_puzzle_sheet()
        puzzle.save()
        for hunt_round in self.cleaned_data["rounds"]:
            print(hunt_round)
            puzzle.rounds.add(hunt_round)
        puzzle.save()
        return puzzle



class UpdatePuzzleForm(forms.Form):
    name = forms.CharField(label="Puzzle Name", max_length=255)
    description = forms.CharField(label="Description", max_length=1000, required=False)
    rounds = forms.MultipleChoiceField(choices=[])
    status = forms.ChoiceField(choices=PuzzleStatus.choices)
    url = forms.URLField(label="Puzzle URL", required=False)
    is_meta = forms.BooleanField(label="Meta?", required=False)
    new_answer = forms.CharField(label="Add Answer", max_length=255, required=False)

    def __init__(self, puzzle, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        hunt = puzzle.hunt

        self.fields["name"].initial = puzzle.name
        self.fields["description"].initial = puzzle.description

        self.fields["rounds"] = forms.MultipleChoiceField(choices=[
            (r.id, r.name) for r in hunt.round_set.all()
        ])

        self.fields["rounds"].initial = [r.id for r in puzzle.rounds.all()]

        self.fields["status"].initial = puzzle.status
        self.fields["url"].initial = puzzle.url
        self.fields["is_meta"].initial = puzzle.is_meta

    def update_puzzle(self, puzzle):

        old_name = puzzle.name
        puzzle.name = self.cleaned_data["name"]
        if old_name != puzzle.name:
            puzzle.rename_puzzle_sheet()

        puzzle.description = self.cleaned_data["description"]


        puzzle.rounds.clear()
        for hunt_round in self.cleaned_data["rounds"]:
            puzzle.rounds.add(hunt_round)

        puzzle.status = self.cleaned_data["status"]
        puzzle.url = self.cleaned_data["url"]
        puzzle.is_meta = self.cleaned_data["is_meta"]
        puzzle.save()

        na = self.cleaned_data["new_answer"]
        if na != "":
            ans = Answer()
            ans.answer_text = na.upper()
            ans.puzzle = puzzle
            ans.save()



class UpdateDiscordUserForm(forms.Form):
    linked_gmail = forms.URLField(label="Google Email", required=False)
    chosen_theme = forms.ChoiceField(choices=Theme.choices)
    chat_color = forms.ChoiceField(choices=Color.choices)

    def __init__(self, discord_user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

        self.fields["linked_gmail"].initial = discord_user.linked_gmail
        self.fields["chosen_theme"].initial = discord_user.chosen_theme
        self.fields["chat_color"].initial = discord_user.chat_color

    def update_user(self, discord_user):
        discord_user.linked_gmail = self.cleaned_data["linked_gmail"]
        discord_user.chosen_theme = self.cleaned_data["chosen_theme"]
        discord_user.chat_color = self.cleaned_data["chat_color"]
        discord_user.save()

puzzles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import authenticate, logout, login


from .models import Hunt, Round, Puzzle, PuzzleStatus, Answer
from .forms import NewPuzzleForm, UpdatePuzzleForm, UpdateDiscordUserForm
from os import getenv
from urllib.parse import quote

DISCORD_CLIENT_ID = getenv("DISCORD_CLIENT_ID")
DISCORD_REDIRECT_URI = getenv("DISCORD_REDIRECT_URI")

from uuid import uuid4

def login_view(request):
    state = uuid4().hex
    request.session["state"] = state
    # request.session["next"] = request.GET.get("next")
    return HttpResponseRedirect(f"https://discord.com/oauth2/authorize?client_id={DISCORD_CLIENT_ID}&response_type=code&redirect_uri={quote(DISCORD_REDIRECT_URI)}&scope=identify&state={state}")

def auth(request):
    if "code" not in request.GET \
        or request.session.get("state") is None \
        or len(request.session.get("state")) != 32 \
        or request.session.get("state") != request.GET.get("state"):
        raise PermissionDenied
    del request.session["state"] # no reuse
    user = authenticate(request, code=request.GET.get("code"))
    if user is not None:
        login(request, user)
        # if request.session["next"] is not None:
        #     return HttpResponseRedirect(request.session["next"])
        return HttpResponseRedirect("/")
    else:
        return HttpResponseRedirect(reverse("puzzles:login"))

def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")

@login_required()
def user_page(request):
    du = request.user.discorduser

    return render(request, "puzzles/userpage.html", {
        "update_user_form": UpdateDiscordUserForm(du)
    })

@login_required()
def update_discord_user(request):
    du = request.user.discorduser
    
    if request.method == "POST":
        form = UpdateDiscordUserForm(du, request.POST)
        if form.is_valid():
            form.update_user(du)

    return HttpResponseRedirect(reverse("puzzles:userpage"))


@login_required()
def bigboard(request, hunt_id):
    hunt = get_object_or_404(Hunt, pk=hunt_id)

    return render(request, "puzzles/bigboard.html", {
        "hunt": hunt,
        "new_puzzle_form": NewPuzzleForm(hunt)
    })

@login_required()
def puzzlepage(request, puzzle_id):
    puzzle = get_object_or_404(Puzzle, pk=puzzle_id)
    return render(request, "puzzles/puzzlepage.html", {
        "puzzle": puzzle,
        "update_puzzle_form": UpdatePuzzleForm(puzzle)
    })

def update(request, puzzle_id):
    puzzle = get_object_or_404(Puzzle, pk=puzzle_id)
    
    if request.method == "POST":
        form = UpdatePuzzleForm(puzzle, request.POST)
        if form.is_valid():
            form.update_puzzle(puzzle)

        # todo: there is definitely a better way to handle answer deletion 
        for answer in puzzle.answer_set.all():
            if request.POST.get(f"delete_answer_{answer.id}", False):
                answer.delete()

    return HttpResponseRedirect(reverse("puzzles:puzzlepage", args=(puzzle.id,)))


def new_round(request, hunt_id):
    hunt = get_object_or_404(Hunt, pk=hunt_id)

    new_round_name = request.POST["new_round"]
    if new_round_name != "" and len(new_round_name) < 255:
        rnd = Round()
        rnd.name = new_round_name
        rnd.hunt = hunt
        rnd.save()

    return HttpResponseRedirect(reverse("puzzles:bigboard", args=(hunt.id,)))


def new_puzzle(request, hunt_id):
    hunt = get_object_or_404(Hunt, pk=hunt_id)
    hunt_round = get_object_or_404(Round, pk=1)

    if hunt_round.hunt.id != hunt.id:
        raise Http404("This round is for a different hunt than the given hunt")

    if request.method == "POST":
        form = NewPuzzleForm(hunt, request.POST)
        if form.is_valid():
            puzzle = form.make_puzzle()
            puzzle.save()
    
    return HttpResponseRedirect(reverse("puzzles:bigboard", args=(hunt.id,)))

def landing(request):
    return render(request, "puzzles/landing.html", {
        "hunts": Hunt.objects.all(),
        "team_name": getenv("TEAM_NAME")
    })

puzzles/templates/puzzles/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% if request.user.is_authenticated %} 
    {% with 'puzzles/themes/'|add:request.user.discorduser.chosen_theme|add:'.css' as css_url %}
    <link rel="stylesheet" href="{% static css_url %}" />
    {% endwith %} {% else %}
    <link rel="stylesheet" href="{% static 'puzzles/themes/mocha.css' %}" 2/>
    {% endif %}
    <link rel="stylesheet" href="{% static 'puzzles/style.css' %}" />
    <title>{% block title %}ℝeservoir{% endblock %}</title>
    <link rel="shortcut icon" type="image/icon" href="{% static 'favicon.ico' %}" >
    {% block head_extra %}{% endblock %}
</head>

<body>
    <div class="nav">
        <span class="nav-left">
            {% block nav-left %}
            
            {% endblock %}
        </span>
        <span class="nav-right">
            {% block nav-right %}
            {% if request.user.is_authenticated %} 
            <a href="{% url 'puzzles:userpage' %}">{{ request.user.discorduser.cached_username }}</a>
            {% else %}
            <a href="{% url 'puzzles:login' %}">Login</a>
            {% endif %}
            {% endblock %}
        </span>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

puzzles/templates/puzzles/bigboard.html
{% extends "puzzles/base.html" %}

{% block title %}ℝeservoir - {{ hunt.name }}{% endblock %}
{% block nav-left %}
<a href="/">Hunts</a> > <b>{{ hunt.name }}</b>
{% endblock %}
{% partialdef puzzlebox %}
    <a href="{% url 'puzzles:puzzlepage' puzzle.id %}"><div class="tooltip puzzle_info status_{{ puzzle.status }}{% if puzzle.is_meta %} meta_info{% endif %}">
        {% if puzzle.description %}
        <span class="tooltip_text">{{ puzzle.description }}</span>
        {% endif %}
        <center><span class="puzzle_name">{% if puzzle.is_meta %}META: {% endif %}{{ puzzle.name }}</span></center>
        {% if puzzle.answer_set.all %}
        <div class="answer_line"></div>
        <center><span class="answer">
        {{ puzzle.answer_set.all| join:", "}}
        </span></center>
        {% endif %}
    </div></a>
{% endpartialdef puzzlebox %}
{% block content %}
<center>
<h1>{{ hunt.name }}</h1>
<div class="total_count countbox"><div class="icon">{% include 'puzzles/icons/puzzle.svg' %}</div><span class="bigboard_number">{{ hunt.total_puzzles }}</span><br>Total Puzzles</div>
<div class="locked_count countbox"><div class="icon">{% include 'puzzles/icons/lock.svg' %}</div><span class="bigboard_number">{{ hunt.num_locked }}</span><br>Locked Puzzles</div>
<div class="solved_count countbox"><div class="icon">{% include 'puzzles/icons/check.svg' %}</div><span class="bigboard_number">{{ hunt.num_solved }}</span><br> Solved Puzzles</div>
<div class="open_count countbox"><div class="icon">{% include 'puzzles/icons/target.svg' %}</div><span class="bigboard_number">{{ hunt.num_available }}</span><br>Avaliable Puzzles</div>
<div class="meta_count countbox"><div class="icon">{% include 'puzzles/icons/layers.svg' %}</div><span class="bigboard_number">{{ hunt.meta_solves }}</span><br>Meta Solves</div>
</center>

<div class="round_info wsiwo">
    <center><h2><i>What Should I Work On?</i></h2></center>
    <div class="puzzles_list">
    {% for puzzle in hunt.top_prio_puzzles %}
    {% partial puzzlebox %}
    {% endfor %}
    </div>
</div>

{% for round in hunt.round_set.all %}
<div class="round_info">
    <center><h2>{{ round.name }}</h2></center>
    <div class="puzzles_list">
    {% for puzzle in round.puzzles_ordered %}
    {% partial puzzlebox %}
    {% endfor %}
    <span class="new_puzzle_icon"><a onclick="showForm('new_puzzle_form', '{{ round.id }}')">{% include 'puzzles/icons/plus.svg' %}</a></span>
    </div>
</div>
{% endfor %}
{% if hunt.roundless_puzzles %}
<div class="round_info">
    <center><h2><i>Puzzles With No Round</i></h2></center>
    <div class="puzzles_list">
    {% for puzzle in hunt.roundless_puzzles %}
    <a href="{% url 'puzzles:puzzlepage' puzzle.id %}"><div class="puzzle_info status_{{ puzzle.status }}{% if puzzle.is_meta %} meta_info{% endif %}">
        <center><span class="puzzle_name">{% if puzzle.is_meta %}META: {% endif %}{{ puzzle.name }}</span></center>
        {% if puzzle.answer_set.all %}
        <div class="answer_line"></div>
        <center><span class="answer">
        {{ puzzle.answer_set.all| join:", "}}
        </span></center>
        {% endif %}
        </div>
    </div></a>
    {% endfor %}
</div>
{% endif %}


<form autocomplete="off" action="{% url 'puzzles:new_round' hunt.id %}" method="post">
{% csrf_token %}
<label for="new_round">Add New Round</label>
<input class="new_round" name="new_round" maxlength="255"></input>
<button type="submit">Add New Round</button>
</form>

<div class="popup_form" id="new_puzzle_form">
        <form autocomplete="off" action="{% url 'puzzles:new_puzzle' hunt.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h3>New Puzzle</h3></legend>
                {{ new_puzzle_form }}
                <button class="cancel_button" onclick="closeForm('new_puzzle_form')" type="button">Cancel</button>
                <button class="submit_button" onclick="closeForm('new_puzzle_form')" type="submit">New Puzzle</button>
            </fieldset>
        </form>
    </div>


<script>
    function showForm(formId, select_id) {
      // Get all forms
      var forms = document.querySelectorAll('.new_puzzle_form');
      // Loop through forms and hide them
      forms.forEach(function(form) {
        form.style.display = 'none';
      });
      // Show the selected form
      var selectedForm = document.getElementById(formId);
      if (selectedForm) {
        selectedForm.style.display = 'block';

        if (select_id) {
            round_select = selectedForm.querySelector("#id_rounds")
            round_select.value = [select_id]
        }

      }
    }

    function closeForm(formId) {
      var selectedForm = document.getElementById(formId);
      if (selectedForm) {
        selectedForm.style.display = 'none';
      }
    }
</script>
{% endblock %}

puzzles/templates/puzzles/landing.html
{% extends "puzzles/base.html" %}
{% block nav-left %}
<b>Hunts</b>
{% endblock %}
{% block content %}
<center><h1>ℝeservoir &mdash; {{ team_name }}</h1></center>

<div class="hunt_list">
{% for hunt in hunts %}
    <center><a href="{% url 'puzzles:bigboard' hunt.id %}"><div class="hunt_info">
        <span class="hunt_left">{{ hunt.name }}</span>
        <span class="hunt_right">
            <span class="total_count">{{ hunt.total_puzzles }}</span>/<span class="locked_count">{{ hunt.num_locked }}</span>/<span class="solved_count">{{ hunt.num_solved }}</span>/<span class="open_count">{{ hunt.num_available }}</span>/<span class="meta_count">{{ hunt.meta_solves }}</span>
        </span>
    </div></a></center>
{% endfor %}
</div>
{% endblock %}

puzzles/templates/puzzles/userpage.html
{% extends "puzzles/base.html" %}

{% block title %}ℝeservoir - {{ request.user.discorduser.cached_username }}{% endblock %}
{% block nav-left %}
<a href="/">Hunts</a>
{% endblock %}
{% block content %}
<center><h1 style="color: var(--{{ request.user.discorduser.chat_color }})">{{ request.user.discorduser.cached_username }}</h1></center>

<center>
<form autocomplete="off" action="{% url 'puzzles:update_discord_user' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h3>Update User Details</h3></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {{ update_user_form }}
    <button class="submit_button" onclick="closeForm('update_puzzle_form')" type="submit">Update</button>
</fieldset>
</form>
</center>
{% endblock %}